/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BlockReport = IDL.Record({
  'id' : IDL.Text,
  'cpf' : IDL.Text,
  'blockDate' : IDL.Text,
  'platform' : IDL.Text,
  'additionalContext' : IDL.Text,
  'blockReason' : IDL.Text,
  'phone' : IDL.Text,
  'driverName' : IDL.Text,
});
export const WorkHistory = IDL.Record({
  'monthlyVehicleFinancing' : IDL.Float64,
  'activeMonths' : IDL.Nat,
  'dailyAvgEarnings' : IDL.Float64,
  'weeklyAvgEarnings' : IDL.Float64,
  'monthlyInsurance' : IDL.Float64,
  'monthlyFuel' : IDL.Float64,
  'monthlyMaintenance' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CeasedProfits = IDL.Record({
  'netLostProfits' : IDL.Float64,
  'totalLostEarnings' : IDL.Float64,
  'totalBlockedDays' : IDL.Nat,
  'totalExpensesDuringBlock' : IDL.Float64,
  'avgDailyEarnings' : IDL.Float64,
});
export const LegalDefense = IDL.Record({
  'blockType' : IDL.Text,
  'structuredDocument' : IDL.Text,
  'suggestedNextSteps' : IDL.Vec(IDL.Text),
  'arguments' : IDL.Vec(IDL.Text),
  'applicableLaws' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DashboardData = IDL.Record({
  'ceasedProfitsCalculations' : IDL.Vec(CeasedProfits),
  'savedDefenses' : IDL.Vec(LegalDefense),
  'workHistories' : IDL.Vec(WorkHistory),
  'blockReports' : IDL.Vec(BlockReport),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlockReport' : IDL.Func([BlockReport], [], []),
  'addWorkHistory' : IDL.Func([WorkHistory], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCeasedProfits' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64],
      [CeasedProfits],
      [],
    ),
  'generateLegalDefense' : IDL.Func([IDL.Text, IDL.Text], [LegalDefense], []),
  'getAllBlockReports' : IDL.Func([], [IDL.Vec(BlockReport)], ['query']),
  'getAllCeasedProfits' : IDL.Func([], [IDL.Vec(CeasedProfits)], ['query']),
  'getAllLegalDefenses' : IDL.Func([], [IDL.Vec(LegalDefense)], ['query']),
  'getAllWorkHistories' : IDL.Func([], [IDL.Vec(WorkHistory)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func([], [DashboardData], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BlockReport = IDL.Record({
    'id' : IDL.Text,
    'cpf' : IDL.Text,
    'blockDate' : IDL.Text,
    'platform' : IDL.Text,
    'additionalContext' : IDL.Text,
    'blockReason' : IDL.Text,
    'phone' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const WorkHistory = IDL.Record({
    'monthlyVehicleFinancing' : IDL.Float64,
    'activeMonths' : IDL.Nat,
    'dailyAvgEarnings' : IDL.Float64,
    'weeklyAvgEarnings' : IDL.Float64,
    'monthlyInsurance' : IDL.Float64,
    'monthlyFuel' : IDL.Float64,
    'monthlyMaintenance' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CeasedProfits = IDL.Record({
    'netLostProfits' : IDL.Float64,
    'totalLostEarnings' : IDL.Float64,
    'totalBlockedDays' : IDL.Nat,
    'totalExpensesDuringBlock' : IDL.Float64,
    'avgDailyEarnings' : IDL.Float64,
  });
  const LegalDefense = IDL.Record({
    'blockType' : IDL.Text,
    'structuredDocument' : IDL.Text,
    'suggestedNextSteps' : IDL.Vec(IDL.Text),
    'arguments' : IDL.Vec(IDL.Text),
    'applicableLaws' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const DashboardData = IDL.Record({
    'ceasedProfitsCalculations' : IDL.Vec(CeasedProfits),
    'savedDefenses' : IDL.Vec(LegalDefense),
    'workHistories' : IDL.Vec(WorkHistory),
    'blockReports' : IDL.Vec(BlockReport),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlockReport' : IDL.Func([BlockReport], [], []),
    'addWorkHistory' : IDL.Func([WorkHistory], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCeasedProfits' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64],
        [CeasedProfits],
        [],
      ),
    'generateLegalDefense' : IDL.Func([IDL.Text, IDL.Text], [LegalDefense], []),
    'getAllBlockReports' : IDL.Func([], [IDL.Vec(BlockReport)], ['query']),
    'getAllCeasedProfits' : IDL.Func([], [IDL.Vec(CeasedProfits)], ['query']),
    'getAllLegalDefenses' : IDL.Func([], [IDL.Vec(LegalDefense)], ['query']),
    'getAllWorkHistories' : IDL.Func([], [IDL.Vec(WorkHistory)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func([], [DashboardData], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };