/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAction {
  'action' : AdminActionType,
  'admin' : Principal,
  'timestamp' : Time,
}
export type AdminActionType = { 'other' : string } |
  { 'blockUser' : { 'userName' : string } } |
  { 'unblockUser' : { 'userName' : string } };
export interface AdminDashboardStats {
  'recentRegistrations' : Array<UserProfile>,
  'blockedUsers' : bigint,
  'activeUsers' : bigint,
  'totalUsers' : bigint,
}
export interface BlockReport {
  'id' : string,
  'cpf' : string,
  'blockDate' : string,
  'platform' : string,
  'additionalContext' : string,
  'blockReason' : string,
  'phone' : string,
  'driverName' : string,
}
export interface CeasedProfits {
  'netLostProfits' : number,
  'totalLostEarnings' : number,
  'totalBlockedDays' : bigint,
  'totalExpensesDuringBlock' : number,
  'avgDailyEarnings' : number,
}
export interface DashboardData {
  'ceasedProfitsCalculations' : Array<CeasedProfits>,
  'savedDefenses' : Array<LegalDefense>,
  'workHistories' : Array<WorkHistory>,
  'blockReports' : Array<BlockReport>,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : string,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export interface LegalDefense {
  'blockType' : string,
  'structuredDocument' : string,
  'suggestedNextSteps' : Array<string>,
  'arguments' : Array<string>,
  'applicableLaws' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'isBlocked' : boolean,
  'name' : string,
  'email' : string,
  'registrationDate' : Time,
}
export interface UserProfileWithPrincipal {
  'principal' : Principal,
  'profile' : UserProfile,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkHistory {
  'monthlyVehicleFinancing' : number,
  'activeMonths' : bigint,
  'dailyAvgEarnings' : number,
  'weeklyAvgEarnings' : number,
  'monthlyInsurance' : number,
  'monthlyFuel' : number,
  'monthlyMaintenance' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlockReport' : ActorMethod<[BlockReport], undefined>,
  'addWorkHistory' : ActorMethod<[WorkHistory], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal, string], undefined>,
  'calculateCeasedProfits' : ActorMethod<
    [bigint, number, number],
    CeasedProfits
  >,
  'generateLegalDefense' : ActorMethod<[string, string], LegalDefense>,
  'getAdminActivityLog' : ActorMethod<[], Array<AdminAction>>,
  'getAdminDashboardStats' : ActorMethod<[], AdminDashboardStats>,
  'getAllBlockReports' : ActorMethod<[], Array<BlockReport>>,
  'getAllCeasedProfits' : ActorMethod<[], Array<CeasedProfits>>,
  'getAllLegalDefenses' : ActorMethod<[], Array<LegalDefense>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfileWithPrincipal>>,
  'getAllWorkHistories' : ActorMethod<[], Array<WorkHistory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<[], DashboardData>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unblockUser' : ActorMethod<[Principal, string], undefined>,
  'uploadGalleryImage' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];