/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TripData = IDL.Record({
  'fines' : IDL.Float64,
  'tolls' : IDL.Float64,
  'distance' : IDL.Float64,
  'fuelCost' : IDL.Float64,
  'maintenance' : IDL.Float64,
});
export const FinancialBreakdown = IDL.Record({
  'fines' : IDL.Float64,
  'tolls' : IDL.Float64,
  'total' : IDL.Float64,
  'distance' : IDL.Float64,
  'fuelCost' : IDL.Float64,
  'maintenance' : IDL.Float64,
});
export const IncidentDetails = IDL.Record({
  'date' : IDL.Text,
  'circumstances' : IDL.Text,
  'location' : IDL.Text,
  'violationType' : IDL.Text,
});
export const LegalDefense = IDL.Record({
  'structuredDocument' : IDL.Text,
  'suggestedNextSteps' : IDL.Vec(IDL.Text),
  'arguments' : IDL.Vec(IDL.Text),
  'applicableLaws' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DashboardData = IDL.Record({
  'savedCalculations' : IDL.Vec(FinancialBreakdown),
  'savedDefenses' : IDL.Vec(LegalDefense),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateFinancialLoss' : IDL.Func([TripData], [FinancialBreakdown], []),
  'generateLegalDefense' : IDL.Func([IncidentDetails], [LegalDefense], []),
  'getAllFinancialLosses' : IDL.Func(
      [],
      [IDL.Vec(FinancialBreakdown)],
      ['query'],
    ),
  'getAllLegalDefenses' : IDL.Func([], [IDL.Vec(LegalDefense)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func([], [DashboardData], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TripData = IDL.Record({
    'fines' : IDL.Float64,
    'tolls' : IDL.Float64,
    'distance' : IDL.Float64,
    'fuelCost' : IDL.Float64,
    'maintenance' : IDL.Float64,
  });
  const FinancialBreakdown = IDL.Record({
    'fines' : IDL.Float64,
    'tolls' : IDL.Float64,
    'total' : IDL.Float64,
    'distance' : IDL.Float64,
    'fuelCost' : IDL.Float64,
    'maintenance' : IDL.Float64,
  });
  const IncidentDetails = IDL.Record({
    'date' : IDL.Text,
    'circumstances' : IDL.Text,
    'location' : IDL.Text,
    'violationType' : IDL.Text,
  });
  const LegalDefense = IDL.Record({
    'structuredDocument' : IDL.Text,
    'suggestedNextSteps' : IDL.Vec(IDL.Text),
    'arguments' : IDL.Vec(IDL.Text),
    'applicableLaws' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const DashboardData = IDL.Record({
    'savedCalculations' : IDL.Vec(FinancialBreakdown),
    'savedDefenses' : IDL.Vec(LegalDefense),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateFinancialLoss' : IDL.Func([TripData], [FinancialBreakdown], []),
    'generateLegalDefense' : IDL.Func([IncidentDetails], [LegalDefense], []),
    'getAllFinancialLosses' : IDL.Func(
        [],
        [IDL.Vec(FinancialBreakdown)],
        ['query'],
      ),
    'getAllLegalDefenses' : IDL.Func([], [IDL.Vec(LegalDefense)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func([], [DashboardData], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };