/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardData {
  'savedCalculations' : Array<FinancialBreakdown>,
  'savedDefenses' : Array<LegalDefense>,
}
export type ExternalBlob = Uint8Array;
export interface FinancialBreakdown {
  'fines' : number,
  'tolls' : number,
  'total' : number,
  'distance' : number,
  'fuelCost' : number,
  'maintenance' : number,
}
export interface GalleryImage {
  'id' : string,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export interface IncidentDetails {
  'date' : string,
  'circumstances' : string,
  'location' : string,
  'violationType' : string,
}
export interface LegalDefense {
  'structuredDocument' : string,
  'suggestedNextSteps' : Array<string>,
  'arguments' : Array<string>,
  'applicableLaws' : Array<string>,
}
export interface TripData {
  'fines' : number,
  'tolls' : number,
  'distance' : number,
  'fuelCost' : number,
  'maintenance' : number,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateFinancialLoss' : ActorMethod<[TripData], FinancialBreakdown>,
  'generateLegalDefense' : ActorMethod<[IncidentDetails], LegalDefense>,
  'getAllFinancialLosses' : ActorMethod<[], Array<FinancialBreakdown>>,
  'getAllLegalDefenses' : ActorMethod<[], Array<LegalDefense>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<[], DashboardData>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadGalleryImage' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];